export const AIRPORT_CODES: Record<string, { city: string; country: string }> = {
  JFK: { city: "New York", country: "US" },
  LAX: { city: "Los Angeles", country: "US" },
  ORD: { city: "Chicago", country: "US" },
  DFW: { city: "Dallas", country: "US" },
  DEN: { city: "Denver", country: "US" },
  SFO: { city: "San Francisco", country: "US" },
  SEA: { city: "Seattle", country: "US" },
  LAS: { city: "Las Vegas", country: "US" },
  MCO: { city: "Orlando", country: "US" },
  MIA: { city: "Miami", country: "US" },
  ATL: { city: "Atlanta", country: "US" },
  BOS: { city: "Boston", country: "US" },
  PHX: { city: "Phoenix", country: "US" },
  IAH: { city: "Houston", country: "US" },
  MSP: { city: "Minneapolis", country: "US" },
  DTW: { city: "Detroit", country: "US" },
  PHL: { city: "Philadelphia", country: "US" },
  LGA: { city: "New York", country: "US" },
  EWR: { city: "Newark", country: "US" },
  SAN: { city: "San Diego", country: "US" },
  TPA: { city: "Tampa", country: "US" },
  PDX: { city: "Portland", country: "US" },
  SLC: { city: "Salt Lake City", country: "US" },
  DCA: { city: "Washington DC", country: "US" },
  IAD: { city: "Washington DC", country: "US" },
  BWI: { city: "Baltimore", country: "US" },
  AUS: { city: "Austin", country: "US" },
  BNA: { city: "Nashville", country: "US" },
  RDU: { city: "Raleigh", country: "US" },
  CLE: { city: "Cleveland", country: "US" },
  CMH: { city: "Columbus", country: "US" },
  IND: { city: "Indianapolis", country: "US" },
  MCI: { city: "Kansas City", country: "US" },
  STL: { city: "St. Louis", country: "US" },
  MSY: { city: "New Orleans", country: "US" },
  SJC: { city: "San Jose", country: "US" },
  OAK: { city: "Oakland", country: "US" },
  SMF: { city: "Sacramento", country: "US" },
  SNA: { city: "Santa Ana", country: "US" },
  HNL: { city: "Honolulu", country: "US" },
  ANC: { city: "Anchorage", country: "US" },
  LHR: { city: "London", country: "GB" },
  CDG: { city: "Paris", country: "FR" },
  FRA: { city: "Frankfurt", country: "DE" },
  AMS: { city: "Amsterdam", country: "NL" },
  MAD: { city: "Madrid", country: "ES" },
  BCN: { city: "Barcelona", country: "ES" },
  FCO: { city: "Rome", country: "IT" },
  MXP: { city: "Milan", country: "IT" },
  ZRH: { city: "Zurich", country: "CH" },
  VIE: { city: "Vienna", country: "AT" },
  MUC: { city: "Munich", country: "DE" },
  DUB: { city: "Dublin", country: "IE" },
  LIS: { city: "Lisbon", country: "PT" },
  CPH: { city: "Copenhagen", country: "DK" },
  OSL: { city: "Oslo", country: "NO" },
  ARN: { city: "Stockholm", country: "SE" },
  HEL: { city: "Helsinki", country: "FI" },
  NRT: { city: "Tokyo", country: "JP" },
  HND: { city: "Tokyo", country: "JP" },
  ICN: { city: "Seoul", country: "KR" },
  PEK: { city: "Beijing", country: "CN" },
  PVG: { city: "Shanghai", country: "CN" },
  HKG: { city: "Hong Kong", country: "HK" },
  SIN: { city: "Singapore", country: "SG" },
  BKK: { city: "Bangkok", country: "TH" },
  SYD: { city: "Sydney", country: "AU" },
  MEL: { city: "Melbourne", country: "AU" },
  AKL: { city: "Auckland", country: "NZ" },
  DXB: { city: "Dubai", country: "AE" },
  DOH: { city: "Doha", country: "QA" },
  IST: { city: "Istanbul", country: "TR" },
  MEX: { city: "Mexico City", country: "MX" },
  CUN: { city: "Cancun", country: "MX" },
  GRU: { city: "Sao Paulo", country: "BR" },
  EZE: { city: "Buenos Aires", country: "AR" },
  SCL: { city: "Santiago", country: "CL" },
  BOG: { city: "Bogota", country: "CO" },
  LIM: { city: "Lima", country: "PE" },
  YYZ: { city: "Toronto", country: "CA" },
  YVR: { city: "Vancouver", country: "CA" },
  YUL: { city: "Montreal", country: "CA" },
  YYC: { city: "Calgary", country: "CA" },
};
