import Foundation

struct Airport {
    let city: String
    let country: String
}

struct AirportCodes {
    static let codes: [String: Airport] = [
        "JFK": Airport(city: "New York", country: "US"),
        "LAX": Airport(city: "Los Angeles", country: "US"),
        "ORD": Airport(city: "Chicago", country: "US"),
        "DFW": Airport(city: "Dallas", country: "US"),
        "DEN": Airport(city: "Denver", country: "US"),
        "SFO": Airport(city: "San Francisco", country: "US"),
        "SEA": Airport(city: "Seattle", country: "US"),
        "LAS": Airport(city: "Las Vegas", country: "US"),
        "MCO": Airport(city: "Orlando", country: "US"),
        "MIA": Airport(city: "Miami", country: "US"),
        "ATL": Airport(city: "Atlanta", country: "US"),
        "BOS": Airport(city: "Boston", country: "US"),
        "PHX": Airport(city: "Phoenix", country: "US"),
        "IAH": Airport(city: "Houston", country: "US"),
        "MSP": Airport(city: "Minneapolis", country: "US"),
        "DTW": Airport(city: "Detroit", country: "US"),
        "PHL": Airport(city: "Philadelphia", country: "US"),
        "LGA": Airport(city: "New York", country: "US"),
        "EWR": Airport(city: "Newark", country: "US"),
        "SAN": Airport(city: "San Diego", country: "US"),
        "TPA": Airport(city: "Tampa", country: "US"),
        "PDX": Airport(city: "Portland", country: "US"),
        "SLC": Airport(city: "Salt Lake City", country: "US"),
        "DCA": Airport(city: "Washington DC", country: "US"),
        "IAD": Airport(city: "Washington DC", country: "US"),
        "BWI": Airport(city: "Baltimore", country: "US"),
        "AUS": Airport(city: "Austin", country: "US"),
        "BNA": Airport(city: "Nashville", country: "US"),
        "RDU": Airport(city: "Raleigh", country: "US"),
        "CLE": Airport(city: "Cleveland", country: "US"),
        "CMH": Airport(city: "Columbus", country: "US"),
        "IND": Airport(city: "Indianapolis", country: "US"),
        "MCI": Airport(city: "Kansas City", country: "US"),
        "STL": Airport(city: "St. Louis", country: "US"),
        "MSY": Airport(city: "New Orleans", country: "US"),
        "SJC": Airport(city: "San Jose", country: "US"),
        "OAK": Airport(city: "Oakland", country: "US"),
        "SMF": Airport(city: "Sacramento", country: "US"),
        "SNA": Airport(city: "Santa Ana", country: "US"),
        "HNL": Airport(city: "Honolulu", country: "US"),
        "ANC": Airport(city: "Anchorage", country: "US"),
        "LHR": Airport(city: "London", country: "GB"),
        "CDG": Airport(city: "Paris", country: "FR"),
        "FRA": Airport(city: "Frankfurt", country: "DE"),
        "AMS": Airport(city: "Amsterdam", country: "NL"),
        "MAD": Airport(city: "Madrid", country: "ES"),
        "BCN": Airport(city: "Barcelona", country: "ES"),
        "FCO": Airport(city: "Rome", country: "IT"),
        "MXP": Airport(city: "Milan", country: "IT"),
        "ZRH": Airport(city: "Zurich", country: "CH"),
        "VIE": Airport(city: "Vienna", country: "AT"),
        "MUC": Airport(city: "Munich", country: "DE"),
        "DUB": Airport(city: "Dublin", country: "IE"),
        "LIS": Airport(city: "Lisbon", country: "PT"),
        "CPH": Airport(city: "Copenhagen", country: "DK"),
        "OSL": Airport(city: "Oslo", country: "NO"),
        "ARN": Airport(city: "Stockholm", country: "SE"),
        "HEL": Airport(city: "Helsinki", country: "FI"),
        "NRT": Airport(city: "Tokyo", country: "JP"),
        "HND": Airport(city: "Tokyo", country: "JP"),
        "ICN": Airport(city: "Seoul", country: "KR"),
        "PEK": Airport(city: "Beijing", country: "CN"),
        "PVG": Airport(city: "Shanghai", country: "CN"),
        "HKG": Airport(city: "Hong Kong", country: "HK"),
        "SIN": Airport(city: "Singapore", country: "SG"),
        "BKK": Airport(city: "Bangkok", country: "TH"),
        "SYD": Airport(city: "Sydney", country: "AU"),
        "MEL": Airport(city: "Melbourne", country: "AU"),
        "AKL": Airport(city: "Auckland", country: "NZ"),
        "DXB": Airport(city: "Dubai", country: "AE"),
        "DOH": Airport(city: "Doha", country: "QA"),
        "IST": Airport(city: "Istanbul", country: "TR"),
        "MEX": Airport(city: "Mexico City", country: "MX"),
        "CUN": Airport(city: "Cancun", country: "MX"),
        "GRU": Airport(city: "Sao Paulo", country: "BR"),
        "EZE": Airport(city: "Buenos Aires", country: "AR"),
        "SCL": Airport(city: "Santiago", country: "CL"),
        "BOG": Airport(city: "Bogota", country: "CO"),
        "LIM": Airport(city: "Lima", country: "PE"),
        "YYZ": Airport(city: "Toronto", country: "CA"),
        "YVR": Airport(city: "Vancouver", country: "CA"),
        "YUL": Airport(city: "Montreal", country: "CA"),
        "YYC": Airport(city: "Calgary", country: "CA"),
    ]

    static func lookup(_ code: String) -> Airport? {
        codes[code.uppercased()]
    }
}
